@echo off
echo Starting Flask Backend...
start "Flask Backend" cmd /k "cd /d D:\Attendence-System-project-v3\attendence_management && python run.py"

echo Starting React Frontend...
start "React Frontend" cmd /k "cd /d D:\Attendence-System-project-v3\attendence_management && npm run dev"

echo Both servers are starting...
echo Flask Backend: http://localhost:5000
echo React Frontend: http://localhost:3000 (or next available port)
echo.
echo Press any key to close this window...
pause
