@echo off
echo Starting Flask Backend...
start "Flask Backend" cmd /k "python app.py"

echo Starting React Frontend...
start "React Frontend" cmd /k "npm run dev"

echo Both servers are starting...
echo Flask Backend: http://localhost:5000
echo React Frontend: http://localhost:3000 (or next available port)
echo.
echo Press any key to close this window...
pause
